CREATE TABLE TAB_PADRAO 
(ID INT AUTO_INCREMENT, DESCRITOR VARCHAR(20), ENDERECO VARCHAR(100) NULL, CIDADE VARCHAR(50) DEFAULT 'Rio De Janeiro',
DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY(ID));

INSERT INTO TAB_PADRAO (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES ('Cliente X', 'Rua Aprovada', 'São Paulo', '2019-01-01');

SELECT * FROM TAB_PADRAO;

INSERT INTO TAB_PADRAO (DESCRITOR)
VALUES ('Cliente Y');