SELECT LTRIM('         OLA') AS RESULTADO;

SELECT RTRIM('OLA            ') AS RESULTADO;

SELECT TRIM('      OLA   ') AS RESULTADO;

SELECT CONCAT('OLA', ' ', 'TUDO BEM?') AS RESULTADO;

SELECT UPPER('ola tudo bem') AS RESULTADO;

SELECT SUBSTRING('OLA, TUDO BEM?', 6) AS RESULTADO;

SELECT SUBSTRING('OLA, TUDO BEM?', 6, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;