SELECT * FROM itens_notas_fiscais;
SELECT * FROM tabela_de_produtos;
SELECT * FROM notas_fiscais;

SELECT TB.SABOR, NF.DATA_VENDA, INF.QUANTIDADE FROM itens_notas_fiscais INF
INNER JOIN notas_fiscais NF
ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_produtos TB
ON INF.CODIGO_DO_PRODUTO = TB.CODIGO_DO_PRODUTO;



SELECT TB.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM itens_notas_fiscais INF
INNER JOIN notas_fiscais NF
ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_produtos TB
ON INF.CODIGO_DO_PRODUTO = TB.CODIGO_DO_PRODUTO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TB.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM itens_notas_fiscais INF
INNER JOIN notas_fiscais NF
ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_produtos TB
ON INF.CODIGO_DO_PRODUTO = TB.CODIGO_DO_PRODUTO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;



/*RESULTADO FINAL*/
SELECT VENDA_SABOR.SABOR, VENDA_SABOR.ANO, VENDA_SABOR.QUANTIDADE, ROUND((VENDA_SABOR.QUANTIDADE/VENDA_TOTAL.QUANTIDADE)*100, 2) AS PARTICIPACAO 
FROM
(SELECT TB.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM itens_notas_fiscais INF
INNER JOIN notas_fiscais NF
ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_produtos TB
ON INF.CODIGO_DO_PRODUTO = TB.CODIGO_DO_PRODUTO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TB.SABOR, YEAR(NF.DATA_VENDA)) AS VENDA_SABOR
INNER JOIN
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM itens_notas_fiscais INF
INNER JOIN notas_fiscais NF
ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_produtos TB
ON INF.CODIGO_DO_PRODUTO = TB.CODIGO_DO_PRODUTO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_SABOR.ANO = VENDA_TOTAL.ANO
ORDER BY PARTICIPACAO DESC;
