SELECT * FROM itens_notas;
SELECT * FROM NOTAS;
SELECT * FROM TAB_FATURAMENTO;

UPDATE itens_notas SET QUANTIDADE = 200
WHERE NUMERO = '105' AND CODIGO = '1002334';

DELETE FROM itens_notas WHERE NUMERO = '105' AND CODIGO = '1002334';

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE AFTER UPDATE ON itens_notas
FOR EACH ROW BEGIN 
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA 
FROM NOTAS A 
INNER JOIN itens_notas B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;
END //

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE AFTER DELETE ON itens_notas
FOR EACH ROW BEGIN 
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA 
FROM NOTAS A 
INNER JOIN itens_notas B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;
END //

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('106', '2019-05-08', '1471156710', '235', '0.10');
INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('106', '1000889', '100', '10');
INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('106', '1002334', '100', '10');

SELECT * FROM TAB_FATURAMENTO;

DELETE FROM itens_notas WHERE NUMERO = '106' AND CODIGO = '1002334';

UPDATE itens_notas SET QUANTIDADE = 400
WHERE NUMERO = '100' AND CODIGO = '1002334';

SELECT * FROM TAB_FATURAMENTO;