CREATE TABLE TAB_FATURAMENTO 
(DATA_VENDA DATE NULL,
TOTAL_VENDA FLOAT);

SELECT * FROM TAB_FATURAMENTO;

SELECT * FROM NOTAS;
SELECT * FROM itens_notas;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('103', '2019-05-08', '1471156710', '235', '0.10');
INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('103', '1000889', '100', '10');
INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('103', '1002334', '100', '10');

SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA 
FROM NOTAS A 
INNER JOIN itens_notas B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('101', '2019-05-08', '1471156710', '235', '0.10');
INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('101', '1000889', '100', '10');
INSERT INTO itens_notas (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('101', '1002334', '100', '10');

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA 
FROM NOTAS A 
INNER JOIN itens_notas B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;

DELETE FROM itens_notas;
DELETE FROM NOTAS;

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT AFTER INSERT ON itens_notas
FOR EACH ROW BEGIN 
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA 
FROM NOTAS A 
INNER JOIN itens_notas B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;
END //